apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-provider
  description: The API Provider
  tags:
    - api
    - tanzu
spec:
  type: openapi
  lifecycle: experimental
  owner: default-team
  definition:
    $text: https://github.com/trisberg/api-provider/blob/main/api-docs.yaml
