apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: api-provider
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: api-provider
    app.tanzu.vmware.com/register-api: "true"
    apps.tanzu.vmware.com/has-tests: "true"
  annotations:
    openapi-spec-endpoint: "/v3/api-docs"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/sample-accelerators/api-provider
      ref:
        branch: main
